### ISSUE TITLE
Broken links in "fault tolerance development work" section

### ISSUE THREAD

**Issue by apjanke** [open-mpi/ompi-www#149]
It looks like the ["Where can I find the fault tolerance development work?" item](https://www.open-mpi.org/faq/?category=ft#ft-location) is out of date. 

* The http://osl.iu.edu/research/ft/ompi-cr/ link is broken; the server is not responding
* The https://svn.mpi-forum.org/trac/mpi-forum-web/wiki/FaultToleranceWikiPage link is broken; 404 response

Maybe these need updating?

**Comment by bosilca** [comment]
Indeed. I will create a PR.
