### ISSUE TITLE
FAQ engine: brackets inside parentheses don't render as fixed-width font

### ISSUE THREAD

**Issue by apjanke** [open-mpi/ompi-www#159]
The FAQ answers use bracket markup (`[...]`) to indicate `<code>`/fixed-width font text runs. However, if you have an open bracket directly inside an open parenthesis, it doesn't get transformed, and renders as literal brackets instead.

For example, in `faq/slurm.inc` at line 32, we have:

https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/faq/slurm.inc#L31-L32

which renders as:

<img width="340" alt="screen shot 2018-12-11 at 6 14 32 pm" src="https://user-images.githubusercontent.com/2618447/49836532-f8f88080-fd70-11e8-9d55-614f86d83352.png">

Maybe just needs a tweak to the regex in `includes/faq_engine.inc`?

https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/includes/faq_engine.inc#L267-L268

Maybe that `([ \t\n\"])` should include a `\(`, or should be a word-boundary pattern (maybe `\b`) instead?

Looks like two bracketed sequences in a row will also not both be transformed.

https://github.com/open-mpi/ompi-www/blob/0e9fa370b74d633b9265e6616c882f0fe157c9d4/faq/tm.inc#L105-L107

Renders as:

<img width="406" alt="screen shot 2018-12-11 at 6 24 45 pm" src="https://user-images.githubusercontent.com/2618447/49836848-37db0600-fd72-11e8-93d5-b51357b22404.png">

**Comment by apjanke** [comment]
Question for maintainers: is there an easy way I can run a local copy of the ompi-www web site so I can test out changes to the PHP code?

And is there a place in the source tree for documentation about the website itself, where doco about running it could be placed?

**Comment by jsquyres** [comment]
We usually just git clone the `ompi-www` repo in any PHP-enabled web server.  It should run just fine.

I'm open to suggestion on an in-tree location for docs -- we can wall it off from the web server via `.htaccess`.

Let me finish all the other PRs before digging into that regexp... I've always known that our "markup"-like language was kinda weak due to simplistic regular expressions (vs. a fully-fledged markup engine).  This set of markup regexp's was written long before such things were popular / easy to install+use.

FWIW: we've noticed that there are markup engines now available that we could probably integrate into our web site, and they probably do a (much?) better job than our regexps.  However, we have a significant "investment" in our existing markup language -- it would take someone a LOT of effort+time to convert from the current text to a new markup.  That's the rationale for why we haven't upgraded.

**Comment by apjanke** [comment]
> We usually just git clone the ompi-www repo in any PHP-enabled web server. It should run just fine.

Cool. I'll give that a try.

> I'm open to suggestion on an in-tree location for docs -- we can wall it off from the web server via .htaccess.

Here's my suggestion: #194, complete with `.htaccess` controls.

I don't mind just sticking with the regexps and tweaking them; they seem to be serving their purpose.

**Comment by jsquyres** [comment]
Here's some simpler regexps that mostly work:

```php
    // Pick up changes in the middle of the string
    $str = preg_replace("/(?=\W)\*(.+?)\*(?=\W)/",
                        "<strong>\\1</strong>", $str);
    $str = preg_replace("/(?=\W)_(.+?)_(?=\W)/",
                        "<em>HELLO \\1 HELLO</em>", $str);
    $str = preg_replace("/(?=\W)\[(.+?)\](?=\W)/",
                        "<code>\\1</code>", $str);
```

That being said, the `*` and `[]` regexps work (and pick up the additional cases you cited) -- the `_` one does not (i.e., it doesn't pick up any `_foo_` cases at all).  I don't understand why, and have kinda run out of time to investigate.  ☹️

**Comment by apjanke** [comment]
Oh, you know what? I bet it's because '*' and '['/']' are themselves non-word characters, so they match `\W`, but '_' is a word character, so it does not match `\W`. And all those are look-forward assertions. So that `(?=\W)\*` is just matching the single `*` character redundantly.

Changing it to `/(?<=\W)_(.+?)_(?=\W)/` seems to work.

What do you think about this variant, which should pick up matches at the beginning, middle, or end of the lines, avoiding the multiple passes with slightly different regexes?

```php
    // Pick up changes anywhere in the line
    $str = preg_replace("/(?<=\W|^)\*(.+?)\*(?=\W|$)/",
                        "<strong>\\1</strong>", $str);
    $str = preg_replace("/(?<=\W|^)_(.+?)_(?=\W|$)/",
                        "<em>\\1</em>", $str);
    $str = preg_replace("/(?<=\W|^)\[(.+?)\](?=\W|$)/",
                        "<code>\\1</code>", $str);
```

I wonder why the current regexes use `[^~]+?` instead of `.+?`? What's the significance of the `~`?

**Comment by jsquyres** [comment]
Oh yes, that's better!

I, too, wondered what the significance was of `~`.  Past Jeff apparently was thinking of something else (and/or just got it wrong)...?

**Comment by apjanke** [comment]
Cool; here's a PR: #224.
