### ISSUE TITLE
"doc/current" symlink seems broken

### ISSUE THREAD

**Issue by apjanke** [open-mpi/ompi-www#162]
The `doc/` directory contains a `current` symlink pointing at `v4.0`. But it seems broken: when I hit it on the web, everything under https://www.open-mpi.org/doc/current/ gives me a 404 error.

In particular, under https://www.open-mpi.org/doc/, the "v4.0 series" link under "Current" is 404, and under https://www.open-mpi.org/faq/?category=tuning#using-paffinity-v1.6, the "mpirun(1) man page for current Open MPI release" link is 404.

I don't know why it's broken; the symlink in the repo seems good to me. Maybe it's a webserver configuration thing about following symlinks? Manually substituting "v4.0" for "current" in the URLs in my web browser address bar resolves correctly, so it doesn't seem like a simple typo or bad filename in the symlink itself.

**Comment by jsquyres** [comment]
Truly weird.

I checked the git repo and confirmed -- just like you -- that the `doc/current` entry is a sym link to `v4.0`.

So I checked the web server itself.  Sure enough, `current` was *not* a sym link: it was a file containing the line `v4.0`.  `rm current; git checkout .` simply restored the file -- not the sym link.  

`git` itself is pretty modern on the web server (v2.17.1), so I can't easily explain why it was wonking out like this.

So I `rm`'ed the `current` file and made the sym link myself.  The web site now works and `git pull` states that everything is up to date.

Fixed -- but weird.
