### ISSUE TITLE
OTPO Mailing Lists link is 404

### ISSUE THREAD

**Issue by apjanke** [open-mpi/ompi-www#212]
https://www.open-mpi.org/community/lists/otpo.php (linked from the "Open Tool for Parameter Optimization" > "Mailing lists" item in the navigation bar) is 404.

**Comment by gpaulsen** [comment]
Thanks for reporting,
Left navigation now routes to https://www.open-mpi.org/projects/otpo/.

**Comment by gpaulsen** [comment]
Oh and to clarify, I believe any mailling list associated with the OTPO project has been retired long ago.
