### ISSUE TITLE
Convert from MD5 / SHA1 sums to something better (SHA256?)

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi-www#255]
Per https://www.zdnet.com/article/sha-1-collision-attacks-are-now-actually-practical-and-a-looming-danger/, it looks like SHA1 is now effectively broken.

Since we don't do any other type of software verification (e.g., signing), we should probably stop using MD5 and SHA1 and upgrade to something else (SHA256?  Even my ancient RHEL6 box has `sha256sum(1)`).

**Comment by jsquyres** [comment]
@bwbarrett Is this something your front-end resources could look at?  It will affect our tarball generation pipeline (and therefore AWS S3) and the web site PHP.

**Comment by gpaulsen** [comment]
Closing.  Looks like all releases have SHA256 hashes reported on tarball download pages (https://www.open-mpi.org/software/ompi/v4.1/)
