### ISSUE TITLE
openfabrics FAQ section claims XRC is supported but has been disabled

### ISSUE THREAD

**Issue by chrissamuel** [open-mpi/ompi-www#28]
According to Jeff here XRC is now disabled for v2, v3 and master (can no longer be enabled via configure):

https://github.com/open-mpi/ompi/pull/4059#issuecomment-326002456

but FAQ says it is supported.

https://www.open-mpi.org/faq/?category=openfabrics#ib-xrc

> 44. Does Open MPI support XRC?
> Yes.
> 
> XRC (eXtended Reliable Connection) decreases the memory consumption of Open MPI and improves its scalability by significantly decreasing number of QPs per machine.
> 
> XRC is available on Mellanox ConnectX family HCAs with OFED 1.4 and later.
> 
> See this FAQ entry for instructions how to tell Open MPI to use XRC receive queues.

I'm not au-fait with the details to update the item otherwise I'd fork and PR (otherwise it'd just say "Disabled as of August 2017").

Thanks!
Chris

**Comment by jsquyres** [comment]
Sorry it took forever to fix this -- but it's finally fixed.  Web site will update within the next few minutes.
