### ISSUE TITLE
MPI_ERR_INTERN: internal error

### ISSUE THREAD

**Issue by aasraoui** [open-mpi/ompi-www#305]
mpirun return an internal error: 

mpirun --allow-run-as-root -np 2 -hostfile mfile.1 ./mdtest -v
[client3:18319] *** An error occurred in MPI_Send
[client3:18319] *** reported by process [1916207105,1]
[client3:18319] *** on communicator MPI_COMM_WORLD
[client3:18319] *** MPI_ERR_INTERN: internal error
[client3:18319] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[client3:18319] ***    and potentially your MPI job)
[1586579937.693331] [client2:18685:0]    ucp_context.c:690  UCX  WARN  network device 'mlx4_0:1' is not available, please use one or more of: 'enp2s0f0'(tcp), 'enp3s0'(tcp)
[root@client2 ~]# 

OS : Centos 7.7
root@client2 ~]# uname -r
3.10.0-1062.18.1.el7.x86_64

hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-5.0-1.0.0.0
[root@client2 ~]# which mpirun
/root/hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-5.0-1.0.0.0-redhat7.7-x86_64/ompi/bin/mpirun

**Comment by jsquyres** [comment]
This is the repository for Open MPI's web site.  If you'd like to file a question or bug report, please file it against [the main Open MPI source code repository](https://github.com/open-mpi/ompi).  You should probably provide a bit more information than you did in this report -- the template issue you'll see when you file the issue will guide you to submit more information.

Thanks!
