### ISSUE TITLE
Empty download pages

### ISSUE THREAD

**Issue by bertwesarg** [open-mpi/ompi-www#517]
Its 2024/12/04 and all download pages are empty for me with two different browsers.

- https://www.open-mpi.org/software/ompi/v5.0/

![Screenshot](https://github.com/user-attachments/assets/cd9b8687-eae0-48d1-8453-4b7b839a2225)

- https://www-lb.open-mpi.org/software/hwloc/v2.11/

![Screenshot](https://github.com/user-attachments/assets/8b213c78-4d88-4b0a-b786-65d7ac491140)

Am I the only one?

**Comment by jsquyres** [comment]
Yikes!

We did just make some changes in our AWS infrastructure -- we must have broken something... checking...

**Comment by jsquyres** [comment]
Hopefully #518 will fix the issue.

**Comment by jsquyres** [comment]
Blarg.  Still another problem (this is all relating to upgrading to PHP 8).  Working on it...

**Comment by jsquyres** [comment]
Web site has been updated.  It'll likely take a few minutes before the CDN reflects the changes.
