### ISSUE TITLE
Cannot subscribe to mailing list

### ISSUE THREAD

**Issue by dalon-work** [open-mpi/ompi-www#519]
I know this isn't the best place for this, but I'm not sure how else to contact the OpenMPI developers. 

It's possible this is an issue on my end. When I go to this webpage: https://www.open-mpi.org/community/lists/ompi.php and click the "subscribe" links (any of them!) I end up at a page that says:

```
This site can’t be reached
lists.open-mpi.org took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT
```
I have tried with my work computer, my personal Linux laptop, and my Android phone, all with the same result. I've tried with Chrome, Firefox, and DuckDuckGo (which is probably Chrome underneath). Or maybe it's just something on my end - I don't know. I'm not a web guy.

**Comment by hppritcha** [comment]
we've been having problems with the Open MPI project mail lists and this is probably an associated problem.  I'll look in to fixing this.

**Comment by hppritcha** [comment]
please try again.  the NMC folks fixed the issue. closing.

**Comment by dalon-work** [comment]
Yes, it works. Thank you!

**Comment by jsquyres** [comment]
@dalon-work I got a notice from our mailing list about a post to ompi-packagers from you -- a post from a non-subscriber.

Our mailman admin still doesn't have everything working properly, so I can't even login to mailman to see what email address you subscribed as.  The email was sent from a @gmail.com address -- is that the one you subscribed from?  We only allow posts from email addresses that are subscribed.  Can you re-post from the email address that you subscribed from?

If the @gmail.com address *is* the one you subscribed from, can you ensure that you clicked through the confirmation email you should have gotten from mailman to complete the subscription process?

**Comment by jsquyres** [comment]
@dalon-work Sorry for all this hassle, BTW.  As @hppritcha mentioned, we've been having problems with our mailing list; it's on my to-do list over the holidays to investigate migrating to Google Groups. ☹️

**Comment by dalon-work** [comment]
I did click the subscribe button - and it let me subscribe with my email and I got a password and everything. Then I sent my email. However, if I go back and try to change password or log in, it says I am not a subscriber, so it must not have stuck.

**Comment by jsquyres** [comment]
It should have sent you an email to confirm your subscription request.  Did you get that?  There's a link to click through in that email to complete the subscription.

**Comment by dalon-work** [comment]
Trying again:

```
ompi-packagers Subscription results

Your subscription request has been received, and will soon be acted upon. Depending on the configuration of this mailing list, your subscription request may have to be first confirmed by you via email, or approved by the list moderator. If confirmation is required, you will soon get a confirmation email which contains further instructions.
```

**Comment by dalon-work** [comment]
Nothing in Spam or Trash folders either. I'll wait for another 30 minutes and see if it shows up.

**Comment by jsquyres** [comment]
It should show up within a minute or so of you subscribing.  So if it still hasn't show up, I take it to mean that the subscription mechanism is still broken.  Sigh.

I can see the message you tried to post to the list:

> Can we have a build of OpenMPI that can be shipped with our product and will perform well across many different kinds of systems?

Yep, that's the goal.

You go on to ask some more detailed questions; do you want to get on a call to chat?  It might be easier to talk higher bandwidth.

**Comment by dalon-work** [comment]
A call would be great. Please send a link to my email, I am free today and Monday.

**Comment by dalon-work** [comment]
Sorry, I should say I am Mountain Time, and am free 9-5 today and Monday, Dec 23 due to the holidays, no one booked my schedule!
